### ISSUE TITLE
User script replacements don't work

### ISSUE THREAD

**Issue by Qwerty-Space** [boxmein/word-to-word#1]
![image](https://cloud.githubusercontent.com/assets/6967592/21194306/566ea5be-c227-11e6-9b5d-f634dc76041c.png)

**Comment by boxmein** [comment]
From the top, the third and fourth entry in `"from"` should be quoted. So like:

    {"from": "Ram", "to": "Rem"},
    {"from": "RAM", "to": "Rem"}

Let me know if this fixes it.

**Comment by Qwerty-Space** [comment]
The comment in the script doesn't say that.  Thanks for the quick reply!


________________________________

**Comment by boxmein** [comment]
No worries! It's not entirely obvious either.

Opened #2 for this.
